ALTER TABLE "Booking"
ADD COLUMN IF NOT EXISTS "consultationMode" TEXT NOT NULL DEFAULT 'AUDIO',
ADD COLUMN IF NOT EXISTS "durationMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS "kundliCount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "amount" INTEGER NOT NULL DEFAULT 0;
